spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    #properties:
     # hibernate:
      #  format_sql: true

  datasource:
    #platform: postgres
    url: jdbc:postgresql://0.0.0.0:5432/clinica
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  flyway:
    baselineOnMigrate: true