spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    #platform: postgres
    url: jdbc:postgresql://172.16.238.10:5432/clinica
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  flyway:
    baselineOnMigrate: true

  security:
    token:
      secret: ${JWT_SECURITY:my-security-key}

server:
  error:
    include-stacktrace: never

